### PR TITLE
New api migration

### PR DESCRIPTION
**Pull request by awgaan**
Everything should work.

Rant: Who on earth thought it would be smart to use two different duration (time) formats in the same API?

### CODE REVIEW

**Comment by awgaan** [comment]
#50. Test it out.

**Comment by solbu** [comment]
Confirmed. It works. 
Doesn't work on kodi 14.0 thou. But on Kodi 17.6 (Mageia 6) it works flawlessly.

**Comment by awgaan** [comment]
@solbu Do you have the crash log for kodi 14.0?

**Comment by solbu** [comment]
> @solbu Do you have the crash log for kodi 14.0?

```
03:00:25 T:139867658176256  NOTICE: Thread LanguageInvoker start, auto delete: false
03:00:25 T:139867658176256  NOTICE: -->Python Interpreter Initialized<--
03:00:26 T:139867658176256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.RuntimeError'>
                                            Error Contents: osrandom engine already registered
                                            Traceback (most recent call last):
                                              File "/home/solbu/.kodi/addons/plugin.video.nrk/main.py", line 18, in <module>
                                                import addon
                                              File "/home/solbu/.kodi/addons/plugin.video.nrk/addon.py", line 29, in <module>
                                                import nrktv
                                              File "/home/solbu/.kodi/addons/plugin.video.nrk/nrktv.py", line 22, in <module>
                                                from requests import Session
                                              File "/home/solbu/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 52, in <module>
                                                from .packages.urllib3.contrib import pyopenssl
                                              File "/home/solbu/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
                                                import OpenSSL.SSL
                                              File "/usr/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
                                                from OpenSSL import rand, crypto, SSL
                                              File "/usr/lib/python2.7/site-packages/OpenSSL/rand.py", line 11, in <module>
                                                from OpenSSL._util import (
                                              File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 4, in <module>
                                                binding = Binding()
                                              File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 95, in __init__
                                                self._ensure_ffi_initialized()
                                              File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 127, in _ensure_ffi_initialized
                                                cls._register_osrandom_engine()
                                              File "/usr/lib64/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 102, in _register_osrandom_engine
                                                raise RuntimeError("osrandom engine already registered")
                                            RuntimeError: osrandom engine already registered
                                            -->End of Python script error report<--
03:00:26 T:139868398426048   ERROR: GetDirectory - Error getting plugin://plugin.video.nrk/browse
03:00:26 T:139868398426048   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nrk/browse) failed
03:00:26 T:139867658176256  NOTICE: Thread BackgroundLoader start, auto delete: false

```

**Comment by awgaan** [comment]
@solbu This seems to be an issue with the package "cryptography". The error has been fixed in newer versions. As kodi plugin authors, we do not have any control over which version of "cryptography" is used. [ref](https://github.com/pyca/cryptography/issues/2287)

**Comment by kristianwh** [comment]
Thanks alot! Works great!

**Comment by alfton** [comment]
it works, but same issue here, nrk3 live not working

**Comment by awgaan** [comment]
@kristianwh @alfton NRK3 doesn't start broadcasting before 19:30 or something. That information is not provided by the API unless a separate request is made for each channel which is something I didn't want to do as there are over 30 tv/radio channels.

**Comment by alfton** [comment]
@awgaan sorry did not think of that one.
Thanks allot for taking the time fixing this plugin.

**Comment by asplundj** [comment]
Works fine on kodi leia on Android

**Comment by laetusmiles** [comment]
Thanks! Only thing which doesn't work for me is subtitles - anyone else?

**Comment by kristianwh** [comment]
> Thanks! Only thing which doesn't work for me is subtitles - anyone else?

Same here. Quite hard to watch Babylon Berlin for me without subtitles ;)

**Pull request merged**
