### PR TITLE
Split search results on div inside li

### PR DESCRIPTION
**Pull request by aslakknutsen**
To avoid finding other li's (e.g. program hosts) inside the search result we split on the div[class=air] which is
the first child element of the search-hit li instead.

In theory something like the following should work as well;

```python
lis = parseDOM(html, 'li', attrs= {'class': '.*search-hit.*'})
```

But for what ever reason, that seems to find only 1 element and that element is _everything_. Which is why I ended up with the div[class=air] instead.

The reason for this pull request is the following script error in Kodi 14 causing the search to fail. The 'li' search end up finding inner 'li' elements describing the program hosts which does not contain a image tag with a alt attribute as assumed should be in a li later in the script.

```python
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
     - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
    Error Type: <type 'exceptions.IndexError'>
    Error Contents: list index out of range
    Traceback (most recent call last):
      File "/storage/.kodi/addons/plugin.video.nrk/default.py", line 270, in <module>
        plugin.run()
      File "/storage/.kodi/addons/plugin.video.nrk/routing.py", line 75, in run
        self._dispatch(path)
      File "/storage/.kodi/addons/plugin.video.nrk/routing.py", line 85, in _dispatch
        view_func(**kwargs)
      File "/storage/.kodi/addons/plugin.video.nrk/default.py", line 211, in search
        plugin.redirect('/search/%s/0' % quote(query))
      File "/storage/.kodi/addons/plugin.video.nrk/routing.py", line 78, in redirect
        self._dispatch(path)
      File "/storage/.kodi/addons/plugin.video.nrk/routing.py", line 85, in _dispatch
        view_func(**kwargs)
      File "/storage/.kodi/addons/plugin.video.nrk/default.py", line 217, in search_results
        results = nrktv.get_search_results(query, page)
      File "/storage/.kodi/addons/plugin.video.nrk/nrktv.py", line 121, in get_search_results
        titles = [parseDOM(li, 'img', ret='alt')[0] for li in lis]
    IndexError: list index out of range
    -->End of Python script error report<--
```

### CODE REVIEW

**Comment by johnkors** [comment]
Another approach is using the autocomplete json.
http://tv.nrk.no/autocomplete?query=kampen%20om%20tungtvannet

**Comment by aslakknutsen** [comment]
@johnkors Json is good.. but it seems to be limited to 10 results?

**Comment by johnkors** [comment]
Yeah, if you want full result sets with paging - stick with screen scraping the search page.

**Comment by aslakknutsen** [comment]
@johnkors any plans for a full json search? :)

**Comment by tamland** [comment]
I believe there's json search in the "secret" mobile API (endpoint `search/{query}`) see `nrktv_mobile.py` for hints;) I don't remember why I haven't ported it over yet so this is fine for now.

**Pull request merged**
